version: 2
updates:
  - package-ecosystem: 'npm'
    open-pull-requests-limit: 99
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'github-actions'
    open-pull-requests-limit: 99
    directory: '/'
    schedule:
      interval: 'daily'
